#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# install-launchagent.sh — install/reload the enforcement LaunchAgent.
#
# What it is: a user-level launchd service that runs `run.sh enforce-policy`
# every 5 minutes. It applies the security guards:
#   - Night window (config) → force arm.
#   - Away from home (router MAC != home) → force arm.
#   - Expired disarm-for → re-arm.
# If none of that applies, it respects a legitimate disarm (home, daytime).
#
# Identifiers:
#   Label:    blink-geofence
#   Plist:    ~/Library/LaunchAgents/blink-geofence.plist
#   Logs:     ~/.config/blink/launchagent.{out,err}
#
# Idempotent: if already loaded, it reloads cleanly (bootout + bootstrap).
# Survives reboot (RunAtLoad=true + StartInterval).
#
# Verify:     launchctl print "gui/$UID/blink-geofence" | head -20
# Uninstall:  launchctl bootout "gui/$UID/blink-geofence" && rm ~/Library/LaunchAgents/blink-geofence.plist
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
LABEL="blink-geofence"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"

mkdir -p "$HOME/Library/LaunchAgents"
mkdir -p "$HOME/.config/blink"

# Plist generated with absolute paths resolved at runtime, so the project is
# portable: if you move the directory, just re-run this script.
cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!--
  LaunchAgent for the blink-geofence project.
  Generated by install-launchagent.sh. Do not edit by hand — re-run the script.
-->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$PROJECT_DIR/run.sh</string>
        <string>enforce-policy</string>
    </array>
    <key>StartInterval</key>
    <integer>300</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$HOME/.config/blink/launchagent.out</string>
    <key>StandardErrorPath</key>
    <string>$HOME/.config/blink/launchagent.err</string>
</dict>
</plist>
EOF

# Bootout previous version if loaded (idempotency).
launchctl bootout "gui/$UID/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$UID" "$PLIST"

echo "✓ LaunchAgent loaded: $LABEL"
echo "  Plist:     $PLIST"
echo "  Interval:  every 300s (5 min)"
echo "  Logs:      ~/.config/blink/launchagent.{out,err}"
echo ""
echo "Uninstall:"
echo "  launchctl bootout gui/\$UID/$LABEL && rm '$PLIST'"
